{% set name = "pyscal-rdf" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyscal_rdf-{{ version }}.tar.gz
  sha256: e33159ff66468a048edd29a62c245e57d77c330fb16dcfd70b9e80298f48bb84

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - ase
    - rdflib
    - pyyaml
    - python-graphviz
    - ipycytoscape
    - networkx
    - spglib
    - pyscal3 >=3.1.7
    - pandas
    - owlready2

test:
  imports:
    - pyscal_rdf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://rdf.pyscal.org
  summary: Ontology based structural manipulation and quering
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
